version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    image: "backend_node"
    ports:
      - "3001:3001"
  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    image: "frontend_react"
    ports:
      - "3000:3000"